GET http://localhost:3001/api/blogs
Content-Type: application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2YTJiOTYzZTg0ZjljYzc2MDA5MDYwMCIsImlhdCI6MTcyMjUxNDYwMiwiZXhwIjoxNzIyNjAxMDAyfQ.bIRJ0HaR1PxLwoiAvaTNtJag26KHI7sYkTM7BFTLfDQ

