GET http://localhost:3001/api/blogs
Content-Type: application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2YTJiOTYzZTg0ZjljYzc2MDA5MDYwMCIsImlhdCI6MTcyMjAwODA0MSwiZXhwIjoxNzIyMDk0NDQxfQ.Hxe501LEM9Ll-MDWQMupDv0pGQxUv1njXimt_ilqjAE

