curl -X POST http://localhost:3001/api/blogs \
-H "Content-Type: application/json" \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2YTJiOTYzZTg0ZjljYzc2MDA5MDYwMCIsImlhdCI6MTcyMjEwNjQzNCwiZXhwIjoxNzIyMTkyODM0fQ.wvE9frjiRyehQoiiFc_xjBpItPRuQoMOUyfKSvX-2A8" \
-d '{
  "title": "frontend",
  "author": "jami",
  "url": "frontend.com",
  "likes": 69,
  "user": {
    "username": "root",
    "name": "salasana",
    "id" : "66a2b963e84f9cc760090600"
  }
}'
